name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Instalar dependencias
        run: pnpm install
      - name: Build
        run: pnpm build || true
      # Puedes agregar más pasos aquí para test, lint, deploy, etc.
